siteTitle = "Blog by George Montgomery"
siteDescr = "Philosophy of Design."
siteAuthor = "George Montgomery"

siteTwitterUrl = "https://twitter.com/Adverbly_"
siteLinkedInUrl = "https://www.linkedin.com/in/montgomerygeorge"
siteGithubUrl = "https://github.com/Adverbly/Adverbly.github.io"
siteEmailUrl = "mailto:george.p.montgomery@gmail.com"

linkPrefix = "www.georgepatrickmontgomery.com"