siteTitle = "Blog by George Montgomery"
siteDescr = "Philosophy of Design. Doing my best to make the best world."
siteAuthor = "George Montgomery"

siteTwitterUrl = "https://twitter.com/Adverbly_"
siteLinkedInUrl = "https://www.linkedin.com/in/montgomerygeorge"
siteGithubUrl = "https://github.com/Adverbly/Adverbly.github.io"
siteEmailUrl = "mailto:george.p.montgomery@gmail.com"

linkPrefix = ""